geoserver:
  url: "http://192.168.33.12:8080/geoserver/rest"
  geowebcache_url: "http://192.168.33.12:8080/geoserver/gwc/rest"
  user: admin
  password: geoserver
ssl:
  cert_file:
  key_file:
  key_pass: ""
